import { colors } from "./colors";

export const tokens = {
  spacing: {
    "spacing-0": 0,
    "spacing-1": 2,
    "spacing-2": 4,
    "spacing-3": 8,
    "spacing-4": 12,
    "spacing-5": 16,
    "spacing-6": 24,
    "spacing-7": 32,
    "spacing-8": 40,
    "spacing-9": 48,
    "spacing-10": 64,
    "spacing-11": 80,
    "spacing-12": 96,
    "spacing-13": 160,
  },
  borderRadius: {
    "radius-0": 0,
    "radius-1": 2,
    "radius-2": 4,
    "radius-3": 8,
    "radius-4": 12,
    "radius-5": 16,
    "radius-6": 24,
    "radius-7": 32,
    "radius-8": 40,
    "radius-9": 48,
    "radius-10": 64,
    "radius-11": 80,
    "radius-12": 96,
    "radius-13": 160,
  },
  borderWidth: {
    "width-0": 0,
    "width-1": 1,
    "width-2": 2,
    "width-4": 4,
    "width-6": 6,
    "width-13": 13,
    "width-18": 18,
  },
  borderColor: {
    light: colors["color-basic-500"],
    dark: colors["color-basic-1000"],
  },
  icon: {
    color: colors["color-basic-600"],
  },
  zIndex: {
    "z-10": 10,
  },
  backgroundColor: {
    "basic-light-1": colors["color-basic-100"],
    "basic-light-2": colors["color-basic-200"],
    "basic-light-3": colors["color-basic-300"],
    "basic-light-4": colors["color-basic-400"],
    "basic-dark-1": colors["color-basic-800"],
    "basic-dark-2": colors["color-basic-900"],
    "basic-dark-3": colors["color-basic-1000"],
    "primary-light-1": colors["color-primary-100"],
    "primary-dark-1": colors["color-primary-800"],
    "primary-light-2": colors["color-primary-200"],
    "primary-dark-2": colors["color-primary-900"],
    "success-light-1": colors["color-success-100"],
    "success-dark-1": colors["color-success-800"],
    "warning-light-1": colors["color-warning-100"],
    "warning-dark-1": colors["color-warning-800"],
    "danger-light-1": colors["color-danger-100"],
    "danger-dark-1": colors["color-danger-800"],
  },
};
